export const SITE = {
  website: "https://geldgedrag.be/",
  author: "Geld & gedrag",
  profile: "",
  desc: "Een rustig essayplatform over geld, gedrag, psychologie, economie en filosofie.",
  title: "Geld & gedrag",
  ogImage: "astropaper-og.jpg",
  lightAndDarkMode: true,
  postPerIndex: 3,
  postPerPage: 6,
  scheduledPostMargin: 15 * 60 * 1000,
  showArchives: false,
  showBackButton: true,
  editPost: {
    enabled: false,
    text: "Bewerk pagina",
    url: "",
  },
  dynamicOgImage: false,
  dir: "ltr",
  lang: "nl",
  timezone: "Europe/Brussels",
} as const;
